### ISSUE TITLE
Optimize default recipe for multiple runs

### ISSUE THREAD

**Issue by AntoineBro** [deep-security/chef#1]
Each time the default recipe is executed the ds_agent rpm is dowloaded , installed  and activated.
It would be better to only download and activate the agent only when necessary.

**Comment by DeepSecurityOpenSourceSupport** [comment]
Hi @AntoineBro,

Starting from [1.1.0](https://github.com/deep-security/chef/releases/tag/1.1.0), the behaviors will be:
- Always download, version comparison can only be done if after the installer have been downloaded.
- If downloaded version is newer, upgrade will be performed. If versions are equals, no re-installation/upgrade will be performed. If downloaded version is older, error will be thrown.
- By default, won't perform reactivation if the ds_agent already activated unless "force_reactivation" attribute is set to true.

This issue will be closed.
